GET http://localhost:3005/api/v1
Accept: application/json

###
GET http://localhost:3005/api/v1/getIntraDayPrices?symbol=MSFT
Accept: application/json

###
GET http://localhost:3005/api/v1/stockQuote?symbol=AAPL
Accept: application/json

###
GET http://localhost:3005/api/v1/getCompanyProfile?symbol=AAPL
Accept: application/json


###
GET http://localhost:3005/api/v1/getTopLosers
Accept: application/json

